name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4
      - run: |
          luarocks install pgmoon
          luarocks install luasocket
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_lua_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.4.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: lua example.lua
